language: python
python: '2.7'
sudo: false
env:
  global:
    - APPENGINE_VERSION=1.9.24
install:
  - cd .. && git clone https://github.com/getpelican/pelican-plugins.git && cd $TRAVIS_BUILD_DIR
  - pip install -r requirements.txt
script:
  - make publish
  - cd $HOME
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_${APPENGINE_VERSION}.zip
  - unzip -q google_appengine_${APPENGINE_VERSION}.zip
  - ./google_appengine/appcfg.py update $TRAVIS_BUILD_DIR --noauth_local_webserver
