name: blog
dependencies:
- beautifulsoup4=4.4.1
- openssl=1.0.2f
- pip=8.0.1
- pygments=2.1
- python=3.5.1
- readline=6.2
- setuptools=19.4
- sqlite=3.9.2
- tk=8.5.18
- wheel=0.26.0
- xz=5.0.5
- zlib=1.2.8
- pip:
  - blinker==1.4
  - docutils==0.12
  - feedgenerator==1.7
  - jinja2==2.8
  - markdown==2.6.5
  - markupsafe==0.23
  - pelican==3.6.3
  - python-dateutil==2.4.2
  - pytz==2015.7
  - six==1.10.0
  - smartypants==1.8.6
  - typogrify==2.0.7
  - unidecode==0.4.19
